### ISSUE TITLE
Cursor can go to the root

### ISSUE THREAD

**Issue by e-matteson** [justinpombrio/synless#109]
If you open a json file and hit `h` (Parent) once, you don't get an error and nothing visually changes. While there, hitting `backspace` gives a "No node to act on here" error and `h` gives a "Cannot move there" error. You then have to hit `l` (FirstChild) twice before the cursor visibly moves to the first object pair.

I assume what's happening is that we're allowing the cursor to move to the root, which we intended to disallow.

**Comment by justinpombrio** [comment]
Fixed by https://github.com/justinpombrio/synless/commit/724a1a94ba3fb9a4ac648d8b65a1bf5244a907bf
