### ISSUE TITLE
Switch between open files

### ISSUE THREAD

**Issue by e-matteson** [justinpombrio/synless#110]
The engine can have multiple files open but there's no way to switch between them. You can't even work around it by opening the previous file again, because you get an error that it's already open.

This shouldn't be too hard. We need to add rhai functions to list documents and switch to a document, and then use them to construct a candidate menu.

**Comment by justinpombrio** [comment]
Fixed by eacb6b0db8c17c1642f0f2cca1764b77bd8bc878
