### ISSUE TITLE
Merge refactored ScreenBuf

### ISSUE THREAD

**Issue by justinpombrio** [justinpombrio/synless#85]
The frontend's ScreenBuf can be simplified if we store the screen position in the ScreenBufIter struct. We did that in the  https://github.com/justinpombrio/synless/tree/screen-buf branch, along with preparations for better unicode support. We're not merging it yet until we figure out what's going on with other synless branches, and whether the latest code is in the master branch or one of the incomplete rewrite branches.

**Comment by e-matteson** [comment]
Done
